---
title: "Descargar datos desde pygbif"
author: "Marius Bottin"
format: gfm
knitr: 
  opts_chunk: 
    fig.path: "./Fig/pygbif"
---

```{r}
#| echo: false
#| include: false
reticulate::use_virtualenv("../env_cifras/")
```


## `pyGbif`: la lista de descargas 

`pyGbif` es un paquete de python que permite manejar la API de GBIF.
En particular, el modulo `occurrences` permite manejar las descargas de conjunto de datos a través de la API.
Sin embargo es importante anotar que el modulo no permite importar los conjuntos de datos, simplemente su descarga.


Primero es importante incluir el archivo .env con los usuarios y contraseñas de GBIF.

```{python}
import os
from dotenv import load_dotenv, dotenv_values
from pygbif import occurrences as occ
from tabulate import tabulate
import pandas as pd
import json
load_dotenv()
print(os.getenv("GBIF_USER"))
```

La lista de descarga permite descargar los metadatos de las descargas presentes en el perfil del usuario de GBIF

```{python}
#| results: asis
#ref_occ_down = occ.download_sql("SELECT gbifid, ScientificName, countryCode FROM occurrence WHERE genus='Espeletia' LIMIT 10")
#occ.download_meta(ref_occ_down)
downList = occ.download_list()
df_downList = pd.json_normalize(downList["results"])
df_downList.columns
df_downList2 = df_downList[['key', 'doi','created','status','request.sendNotification','downloadLink']]
print(tabulate(df_downList2, headers = 'keys', tablefmt = 'github'))
```

Podemos utilizar esta lista para probar si ya se descargo, a través de la API SQL una consulta SQL (Nota: imagino que cuando son consultas complejas, podríamos tener problemas con los cambios de linea):



```{python}
def is_in_my_download_list(sql_query, limit=20):
  downList = occ.download_list(limit=limit)
  df_downList = pd.json_normalize(downList["results"])
  df_downList_SQLok = df_downList[df_downList["request.sql"] == sql_query]
  tableOK = df_downList_SQLok.query('status == "PREPARING" or status == "RUNNING" or status == "SUCCEEDED"')
  sizeMatch = tableOK.size
  return sizeMatch>0

query = "SELECT gbifid, ScientificName, countryCode FROM occurrence WHERE genus='Espeletia' LIMIT 10"
is_in_my_download_list(query)
```

Incluso podemos mirar cual es el "key" de descarga que corresponde a la consulta SQL:

```{python}
def get_query_key(sql_query, limit=20):
  downList = occ.download_list(limit=limit)
  df_downList = pd.json_normalize(downList["results"])
  df_downList_SQLok = df_downList[df_downList["request.sql"] == sql_query]
  tableOK = df_downList_SQLok.query('status == "PREPARING" or status == "RUNNING" or status == "SUCCEEDED"')
  lastKey = tableOK['key'].values[0]
  return lastKey

get_query_key(query)
```


## Hacer una función Wait


Gracias a la función `download_meta` podemos mirar el estatus de la descarga, que cuando todo va bien pasa de 'PREPARING' a 'RUNNING' a 'SUCCEEDED'

```{python}
def download_status(key):
  status = occ.download_meta(key)['status']
  return status
  
download_status(get_query_key(query))
```

Entonces, podemos crear una función wait, para esperar que el estatus llegue a 'SUCCEEDED', y muestre los cambios de estatus:

```{python}
"""
Potential statuses of a download in gbif PREPARING, RUNNING, SUCCEEDED, CANCELLED, KILLED, FAILED, SUSPENDED, FILE_ERASED
"""
import time

def download_wait(key, freqTest=60):
  currentStatus = download_status(key)
  print("status:", currentStatus)
  while currentStatus != 'SUCCEEDED':
    time.sleep(freqTest)
    previousStatus = currentStatus
    currentStatus = download_status(key)
    if currentStatus in ['CANCELLED', 'KILLED', 'FAILED', 'SUSPENDED', 'FILE_ERASED']:
      raise Exception("The key do not correspond to a dowloadable status: " + currentStatus)
    if currentStatus != previousStatus:
      print("status:", currentStatus)
  return key

download_wait(get_query_key(query))

query = "SELECT gbifid, ScientificName, countryCode FROM occurrence WHERE genus='Espeletia' LIMIT 2"
if not is_in_my_download_list(query):
  key = occ.download_sql(query)
else:
  key=download_wait(get_query_key(query))
  
```

## Crear la consulta geográfica con el WKT

Para manejar datos espaciales vectoriales, los paquetes Python más utilizados son:

* `shapely` que parece ser la base de codigo de muchos otros paquetes
* `fiona` que parece ser una solución un poco más completa, pero algunos usuarios han mencionado dificultades de instalación
* `geopandas` que permite 

```{python}
import fiona
import shapely
from shapely.plotting import plot_polygon
#from shapely.geometry import shape,Polygon, MultiPolygon
import matplotlib.pyplot as plt

with fiona.open("../../data_sintesis-biocifras/RegionesMaritimas.shp") as src:
    for feature in src:
        # Convert the record geometry to a Shapely object
        geom_rm = shape(feature['geometry'])
        print(geom_rm.geom_type)
        
fig, ax = plt.subplots()
for poly in geom_rm:
    plot_polygon(poly, ax=ax, add_points=False, color='blue', alpha=0.5)
plt.show()

with fiona.open("../../data_sintesis-biocifras/MGN_DPTO_POLITICO_2023.shp") as src:
    for feature in src:
        # Convert the record geometry to a Shapely object
        geom_col = shape(feature['geometry'])
        print(geom_col.geom_type)

geom_multi = shapely.union_all([geom_rm,geom_col])
geom_polys = list(geom_multi.geoms)

fig, ax = plt.subplots()
for poly in geom_polys:
    plot_polygon(poly, ax=ax, add_points=False, color='blue', alpha=0.5)
plt.show()

```

